version: '3.8'

services:

  # Nginx service
  nginx:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    volumes:
      - ./src/lms:/var/www/lms
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - lms

  # Ims service
  lms:
    build: 
      context: ./.docker/lms
    working_dir: /var/www/lms
    volumes:
      - ./src/lms:/var/www/lms

  # Mysql service
  mysql:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=lms
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - lms_mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

# Volumes
volumes:
  lms_mysqldata:
